# fly.toml app configuration file generated for earthdawn-discord-bot on 2024-12-23T10:13:25-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'earthdawn-discord-bot'
primary_region = 'ewr'

[build]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
